plugin/drop-zone/Controller/API/DropzoneToolController.php
<?php

/*
 * This file is part of the Claroline Connect package.
 *
 * (c) Claroline Consortium <consortium@claroline.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Claroline\DropZoneBundle\Controller\API;

use Claroline\AppBundle\Annotations\ApiMeta;
use Claroline\AppBundle\Controller\AbstractCrudController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration as EXT;

/**
 * @ApiMeta(class="Claroline\DropZoneBundle\Entity\DropzoneTool")
 * @EXT\Route("/dropzonetool")
 */
class DropzoneToolController extends AbstractCrudController
{
    public function getName()
    {
        return 'dropzone_tool';
    }
}

plugin/drop-zone/Resources/views/notification/notification_correction_report.html.twig
{% if notification.details.report.dropId is defined  %}
    <a href="{{ path('claro_dropzone_detail_drop', {'dropzoneId' : notification.details.report.dropzoneId, 'dropId': notification.details.report.dropId}) }}"
       target="_blank"><span
                class="fa fa-exclamation-triangle"></span>{{ notification.actionKey|trans({'%dropzone%' : notification.details.resource.name}, 'notification') }}
    </a>
{% else %}
    <a href="#"><span
                class="fa fa-exclamation-triangle"></span>{{ notification.actionKey|trans({'%dropzone%' : notification.details.resource.name}, 'notification') }}
    </a>
{% endif %}

plugin/drop-zone/Resources/views/notification/notification_drop_end.html.twig
<a href="{{ path('claro_dropzone_detail_drop', {'dropzoneId' : notification.details.dropzone.id, 'dropId': notification.details.drop.id}) }}"
   target="_blank">{{ notification.actionKey|trans({'%dropzone%' : notification.details.resource.name}, 'notification') }}</a>

plugin/drop-zone/Resources/views/notification/notification_drop_grade_available.html.twig
{% if notification.details.dropzoneId is defined  %}
    <a href="{{ path('claro_dropzone_detail_dropzone', {'dropzoneId' : notification.details.dropzoneId}) }}" target="_blank"><span
                class="fa fa-exclamation-triangle"></span> {{ notification.actionKey|trans({'%dropzone%' : notification.details.resource.name}, 'notification') }}
    </a>
{% else %}
    <a href="#"><span
                class="fa fa-exclamation-triangle"></span>{{ notification.actionKey|trans({'%dropzone%' : notification.details.resource.name}, 'notification') }}
    </a>
{% endif %}

plugin/drop-zone/Resources/views/notification/notification_drop_report.html.twig
{% if notification.details.report.dropId is defined  %}
    <a href="{{ path('claro_dropzone_detail_drop', {'dropzoneId' : notification.details.report.dropzoneId, 'dropId': notification.details.report.dropId}) }}"
       target="_blank"><span
                class="fa fa-exclamation-triangle"></span>{{ notification.actionKey|trans({'%dropzone%' : notification.details.resource.name}, 'notification') }}
    </a>
{% else %}
    <a href="#"><span
                class="fa fa-exclamation-triangle"></span>{{ notification.actionKey|trans({'%dropzone%' : notification.details.resource.name}, 'notification') }}
    </a>
{% endif %}

plugin/drop-zone/Resources/views/notification/notification_dropzone_manual_state_changed.html.twig
	<a href="{{ path('claro_dropzone_detail_dropzone', {'dropzoneId' : notification.details.resource.id}) }}" target="_blank">
		{{ notification.actionKey|trans({
			'%dropzone%' : notification.details.resource.name, 
			'%newState%' : notification.details.newState|trans({
			},'dropzone')
		}, 'notification') }}
	</a>

plugin/drop-zone/Resources/views/notification/notification_item.html.twig
{% extends 'IcapNotificationBundle:templates:notification.html.twig' %}
{% set avatarUrlPrefix = asset('uploads/pictures/') %}

{% block notificationText %}
    {% if notification.userId is not empty and notification.details.doer is defined and constant('Claroline\\DropZoneBundle\\Event\\Log\\LogDropGradeAvailableEvent::ACTION') != notification.actionKey %}
        <a href="{{ path('claro_user_profile', {'user' : notification.userId}) }}"><strong>{{ notification.details.doer.firstName ~ ' ' ~ notification.details.doer.lastName }}</strong></a>
    {% else %}
        <strong>{{ systemName }}</strong>
    {% endif %}
    {% if constant('Claroline\\DropZoneBundle\\Event\\Log\\LogDropReportEvent::ACTION') == notification.actionKey %}
        {#    DROP REPORT  #}
        {% include 'ClarolineDropZoneBundle:Notification:notification_drop_report.html.twig' %}
    {% elseif constant('Claroline\\DropZoneBundle\\Event\\Log\\LogCorrectionReportEvent::ACTION') == notification.actionKey %}
        {#    CORRECTION  REPORT  #}
        {% include 'ClarolineDropZoneBundle:Notification:notification_correction_report.html.twig' %}
    {% elseif constant('Claroline\\DropZoneBundle\\Event\\Log\\LogDropGradeAvailableEvent::ACTION') == notification.actionKey %}
        {#    DROP GRADE AVAILABLE  #}
        {% include 'ClarolineDropZoneBundle:Notification:notification_drop_grade_available.html.twig' %}
    {% elseif constant('Claroline\\DropZoneBundle\\Event\\Log\\LogDropzoneManualStateChangedEvent::ACTION') == notification.actionKey %}
        {#    MANUAL STATE CHANGED  #}
        {% include 'ClarolineDropZoneBundle:Notification:notification_dropzone_manual_state_changed.html.twig' %}
    {% elseif constant('Claroline\\DropZoneBundle\\Event\\Log\\LogDropEndEvent::ACTION') == notification.actionKey %}
        {#    DROP END  #}
        {% include 'ClarolineDropZoneBundle:notification:notification_drop_end.html.twig' %}

    {% endif %}
{% endblock %}