plugin/blog/Entity/Statusable.php
<?php

namespace Icap\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\VirtualProperty;

/**
 * @ExclusionPolicy("all")
 */
class Statusable
{
    const STATUS_UNPUBLISHED = 0;
    const STATUS_PUBLISHED = 1;

    /**
     * @var array
     */
    protected $statusList = [
        self::STATUS_PUBLISHED,
        self::STATUS_UNPUBLISHED,
    ];

    /**
     * @var int
     *
     * @ORM\Column(type="smallint")
     */
    protected $status = self::STATUS_UNPUBLISHED;

    /**
     * @param int $status
     *
     * @return Statusable
     *
     * @throws \InvalidArgumentException
     */
    public function setStatus($status)
    {
        if (!in_array($status, $this->statusList)) {
            throw new \InvalidArgumentException(sprintf('Invalid status for %s.', __CLASS__));
        }
        $this->status = $status;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return Post
     */
    public function publish()
    {
        return $this->setStatus(self::STATUS_PUBLISHED);
    }

    /**
     * @return Post
     */
    public function unpublish()
    {
        return $this->setStatus(self::STATUS_UNPUBLISHED);
    }

    /**
     * @return bool
     * @VirtualProperty
     * @Groups({"blog_list", "blog_post"})
     */
    public function isPublished()
    {
        return $this->getStatus() === self::STATUS_PUBLISHED;
    }
}

plugin/blog/Resources/views/log/log_details.html.twig
{% extends 'ClarolineCoreBundle:log:view_details.html.twig' %}

{% block logDetailsContext %}
    {{ parent() }}
    {% if constant('Icap\\BlogBundle\\Event\\Log\\LogPostCreateEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_post_create.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostReadEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_post_read.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostUpdateEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_post_update.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostDeleteEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_post_delete.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostPublishEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_post_publish.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentCreateEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_comment_create.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentDeleteEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_comment_delete.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentUpdateEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_comment_update.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentPublishEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_comment_publish.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogBlogConfigureEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_blog_configure.html.twig' %}
    {% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogBlogConfigureBannerEvent::ACTION') == log.action %}
        {% include 'IcapBlogBundle:log:log_details_blog_configure.html.twig' %}
    {% endif %}
{% endblock %}

plugin/blog/Resources/views/log/log_details_blog_configure.html.twig
{% if log.details.blog is defined %}
    {% if log.getDetails().blog.changeSet is defined and log.getDetails().blog.changeSet|length > 0 %}
    <div>
        <h4>{{ ('log_change_set')|trans({}, 'log') }}</h4>
        <h5>{{ ('log_old_values')|trans({}, 'log') }}</h5>
        {% set changeSet = log.getDetails().blog.changeSet %}
        <dl class="dl-horizontal">
            {% for key, values in changeSet %}
                <dt>{{ key|trans({}, 'log') }}</dt>
                {% if values[0] is null %}
                    <dd>...</dd>
                {% else %}
                    {% if key == 'icon' %}
                        <dd><img width="71" heigth="80" src="{{asset(values[0])}}"/></dd>
                    {% elseif values[0] is sameas(true) %}
                        <dd>{{ ('yes')|trans({}, 'platform') }}</dd>
                    {% elseif values[0] is sameas(false) %}
                        <dd>{{ ('no')|trans({}, 'platform') }}</dd>
                    {% else %}
                        <dd>{{ values[0]|raw }}</dd>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </dl>
        <h5>{{ ('log_new_values')|trans({}, 'log') }}</h5>
        <dl class="dl-horizontal">
            {% for key, values in changeSet %}
                <dt>{{ key|trans({}, 'log') }}</dt>
                {% if values[1] is null %}
                    <dd>...</dd>
                {% else %}
                    {% if key == 'icon' %}
                        <dd><img width="71" heigth="80" src="{{asset(values[1])}}"/></dd>
                    {% elseif values[1] is sameas(true) %}
                        <dd>{{ ('yes')|trans({}, 'platform') }}</dd>
                    {% elseif values[1] is sameas(false) %}
                        <dd>{{ ('no')|trans({}, 'platform') }}</dd>
                    {% else %}
                        <dd>{{ values[1]|raw }}</dd>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </dl>
    </div>
    {% endif %}
{% endif %}

plugin/blog/Resources/views/log/log_details_comment_create.html.twig
{% if log.details.comment is defined %}
    <h4>{{ ('log_created_comment')|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_comment_content')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.comment.comment }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_comment_delete.html.twig
{% if log.details.comment is defined %}
    <h4>{{ ('log_deleted_comment')|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_comment_author')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.comment.author }}</dd>
        <dt>{{ ('log_comment_content')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.comment.content|raw }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_comment_publish.html.twig
{% if log.details.comment is defined %}
    {% set eventName = 'log_published_comment' %}
    {% if log.details.comment.published == false %}
        {% set eventName = 'log_unpublished_comment' %}
    {% endif %}
    <h4>{{ eventName|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_comment_content')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.comment.comment }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_comment_update.html.twig
{% if log.details.comment is defined %}
    {% if log.getDetails().comment.changeSet is defined and log.getDetails().comment.changeSet|length > 0 %}
        <div>
            <h4>{{ ('log_change_set')|trans({}, 'log') }}</h4>
            <h5>{{ ('log_old_values')|trans({}, 'log') }}</h5>
            {% set changeSet = log.getDetails().comment.changeSet %}
            <dl class="dl-horizontal">
                {% for key, values in changeSet %}
                    <dt>{{ key|trans({}, 'log') }}</dt>
                    {% if values[0] is null %}
                        <dd>...</dd>
                    {% else %}
                        {% if key == 'icon' %}
                            <dd><img width="71" heigth="80" src="{{asset(values[0])}}"/></dd>
                        {% elseif values[0] is sameas(true) %}
                            <dd>{{ ('yes')|trans({}, 'platform') }}</dd>
                        {% elseif values[0] is sameas(false) %}
                            <dd>{{ ('no')|trans({}, 'platform') }}</dd>
                        {% else %}
                            <dd>{{ values[0]|raw }}</dd>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </dl>
            <h5>{{ ('log_new_values')|trans({}, 'log') }}</h5>
            <dl class="dl-horizontal">
                {% for key, values in changeSet %}
                    <dt>{{ key|trans({}, 'log') }}</dt>
                    {% if values[1] is null %}
                        <dd>...</dd>
                    {% else %}
                        {% if key == 'icon' %}
                            <dd><img width="71" heigth="80" src="{{asset(values[1])}}"/></dd>
                        {% elseif values[1] is sameas(true) %}
                            <dd>{{ ('yes')|trans({}, 'platform') }}</dd>
                        {% elseif values[1] is sameas(false) %}
                            <dd>{{ ('no')|trans({}, 'platform') }}</dd>
                        {% else %}
                            <dd>{{ values[1]|raw }}</dd>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </dl>
        </div>
    {% endif %}
{% endif %}

plugin/blog/Resources/views/log/log_details_post.html.twig
{% if log.details.post is defined %}
    <h4>{{ ('log_created_post')|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_post_title')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.post.title }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_post_create.html.twig
{% if log.details.post is defined %}
    <h4>{{ ('log_created_post')|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_post_title')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.post.title }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_post_delete.html.twig
{% if log.details.post is defined %}
    <h4>{{ ('log_deleted_post')|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_post_title')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.post.title }}</dd>
        <dt>{{ ('log_post_author')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.post.author }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_post_publish.html.twig
{% if log.details.post is defined %}
    {% set eventName = 'log_published_post' %}
    {% if log.details.post.published == false %}
        {% set eventName = 'log_unpublished_post' %}
    {% endif %}
    <h4>{{ eventName|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_post_title')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.post.title }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_post_read.html.twig
{% if log.details.post is defined %}
    <h4>{{ ('log_readed_post')|trans({}, 'log') }}</h4>

    <dl class="dl-horizontal">
        <dt>{{ ('log_post_title')|trans({}, 'log') }}</dt>
        <dd>{{ log.details.post.title }}</dd>
    </dl>
{% endif %}

plugin/blog/Resources/views/log/log_details_post_update.html.twig
{% if log.details.post is defined %}
    {% if log.getDetails().post.changeSet is defined and log.getDetails().post.changeSet|length > 0 %}
    <div>
        <h4>{{ ('log_change_set')|trans({}, 'log') }}</h4>
        <h5>{{ ('log_old_values')|trans({}, 'log') }}</h5>
        {% set changeSet = log.getDetails().post.changeSet %}
        <dl class="dl-horizontal">
            {% for key, values in changeSet %}
                <dt>{{ key|trans({}, 'log') }}</dt>
                {% if values[0] is null %}
                    <dd>...</dd>
                {% else %}
                    {% if key == 'icon' %}
                        <dd><img width="71" heigth="80" src="{{asset(values[0])}}"/></dd>
                    {% elseif values[0] is sameas(true) %}
                        <dd>{{ ('yes')|trans({}, 'platform') }}</dd>
                    {% elseif values[0] is sameas(false) %}
                        <dd>{{ ('no')|trans({}, 'platform') }}</dd>
                    {% else %}
                        <dd>{{ values[0]|raw }}</dd>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </dl>
        <h5>{{ ('log_new_values')|trans({}, 'log') }}</h5>
        <dl class="dl-horizontal">
            {% for key, values in changeSet %}
                <dt>{{ key|trans({}, 'log') }}</dt>
                {% if values[1] is null %}
                    <dd>...</dd>
                {% else %}
                    {% if key == 'icon' %}
                        <dd><img width="71" heigth="80" src="{{asset(values[1])}}"/></dd>
                    {% elseif values[1] is sameas(true) %}
                        <dd>{{ ('yes')|trans({}, 'platform') }}</dd>
                    {% elseif values[1] is sameas(false) %}
                        <dd>{{ ('no')|trans({}, 'platform') }}</dd>
                    {% else %}
                        <dd>{{ values[1]|raw }}</dd>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </dl>
    </div>
    {% endif %}
{% endif %}

plugin/blog/Resources/views/log/log_list_item.html.twig
{% set post %}
    {% include 'IcapBlogBundle:log:log_list_item_post.html.twig' %}
{% endset %}

{% set resource %}
    {% include 'ClarolineCoreBundle:log:view_list_item_resource.html.twig' %}
{% endset %}

{% if constant('Icap\\BlogBundle\\Event\\Log\\LogPostCreateEvent::ACTION') == log.action %}
    {{ 'log.blog.create_post'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostReadEvent::ACTION') == log.action %}
    {{ 'log.blog.read_post'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostUpdateEvent::ACTION') == log.action %}
    {{ 'log.blog.update_post'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostDeleteEvent::ACTION') == log.action %}
    {{ 'log.blog.delete_post'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogPostPublishEvent::ACTION') == log.action %}
    {{ 'log.blog.publish_post'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentCreateEvent::ACTION') == log.action %}
    {{ 'log.blog.create_comment'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentUpdateEvent::ACTION') == log.action %}
    {{ 'log.blog.update_comment'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentDeleteEvent::ACTION') == log.action %}
    {{ 'log.blog.delete_comment'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogCommentPublishEvent::ACTION') == log.action %}
    {{ 'log.blog.publish_comment'|trans({'%blog%': resource, '%post%': post}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogBlogConfigureEvent::ACTION') == log.action %}
    {{ 'log.blog.configure'|trans({'%blog%': resource}, 'log')|raw }}
{% elseif constant('Icap\\BlogBundle\\Event\\Log\\LogBlogConfigureBannerEvent::ACTION') == log.action %}
    {{ 'log.blog.configure_banner'|trans({'%blog%': resource}, 'log')|raw }}
{% else %}
    no default text
{% endif %}

plugin/blog/Resources/views/log/log_list_item_post.html.twig
{% if log.details.post is defined %}
    <a href="{{ path('icap_blog_post_view', {'blogId': log.details.post.blog, 'postSlug': log.details.post.slug }) }}"><strong>{{ log.details.post.title }}</strong></a>
{% endif %}